const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout
	];
};
self.C3_JsPropNameTable = [
	{telaDeInício: 0},
	{fundoplay: 0},
	{SetadoPlay: 0},
	{Toque: 0},
	{fase1: 0},
	{Vulnerable: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Flash: 0},
	{player: 0},
	{Sólido: 0},
	{Colisaodomapa: 0},
	{Teclado: 0},
	{Solid: 0},
	{Serra: 0},
	{plataforma: 0},
	{Platform: 0},
	{Sine: 0},
	{enemyfase1: 0},
	{tubofase1: 0},
	{fase2: 0},
	{tubofase2: 0},
	{boss: 0},
	{Sprite: 0},
	{Vida_HUD_0D7u5: 0},
	{gameover: 0},
	{No: 0},
	{Yes: 0},
	{gameoverimg: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Audio: 0},
	{Vida: 0}
];

self.InstanceType = {
	telaDeInício: class extends self.ITiledBackgroundInstance {},
	fundoplay: class extends self.ISpriteInstance {},
	SetadoPlay: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	fase1: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	Colisaodomapa: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Serra: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	enemyfase1: class extends self.ISpriteInstance {},
	tubofase1: class extends self.ISpriteInstance {},
	fase2: class extends self.ITiledBackgroundInstance {},
	tubofase2: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Vida_HUD_0D7u5: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	No: class extends self.ISpriteInstance {},
	Yes: class extends self.ISpriteInstance {},
	gameoverimg: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {}
}